ALTER TABLE user_profiles
    ADD COLUMN IF NOT EXISTS headline TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS education TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS occupation TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS location TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS website_url TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cover_object_id UUID;
