CREATE TABLE IF NOT EXISTS discussion_rooms (
    id UUID PRIMARY KEY,
    article_id UUID NOT NULL UNIQUE REFERENCES articles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
